import Head from 'next/dist/shared/lib/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import BlogPage from '../components/BlogSection/BlogPage'
export default function Blogs() {
  return (
    <div>
      <Head>
        <title>Umer Shabir</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css'
          integrity='sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=='
          crossOrigin='anonymous'
          referrerpolicy='no-referrer'
        />
      </Head>
      <div className='flex flex-col'>
        <Navbar />
        <main>
          <BlogPage />
        </main>
        <Footer />
      </div>
    </div>
  )
}
