// dependencies
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import HeroSection from '../components/HeroSection'
import Services from '../components/Services'
import WorkingHistory from '../components/WorkingHistory'
import Footer from '../components/Footer'
import BlogSection from '../components/BlogSection'
import JobHistory from '../components/JobHistory'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Umer Shabir</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css'
          integrity='sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=='
          crossOrigin='anonymous'
          referrerpolicy='no-referrer'
        />
      </Head>
      <div className='flex flex-col'>
        <Navbar />
        <main>
          <HeroSection />
          <JobHistory />
          <Services />
          <WorkingHistory />
          <BlogSection />
        </main>
        <Footer />
      </div>
    </div>
  )
}
